name: deploy-portfolio

on:
  push:
    branches:
    - main  
jobs:
  build:  

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name : Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest .


      - name : push docker image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
      
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f 2048-namespace.yaml
          kubectl apply -f 2048-deployment.yaml
          kubectl apply -f 2048-service.yaml
          kubectl apply -f dep.yml
          kubectl apply -f ser.yml
          kubectl apply -f 2048-ingress.yml
